# Generated by Django 3.1.7 on 2022-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='information',
        ),
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
